### ISSUE TITLE
'SurrogateModel' object has no attribute 'nameGM'

### ISSUE THREAD

**Issue by annehulsey** [kuanshi/shaf-ida#3]
The change from Sep 30th to line 50 in StructuralSurrogateModel.py broke line 52. I think it would be sufficient to change line 52 to for "gmtag in temp_nameGM:" but I am not sure whether that would cause an issue with the data sorting in lines 58-64.

Note, I added this on my computer and tried to push to the GitHub for you to accept but I got an error with permissions.

**Comment by kuanshi** [comment]
Thank you @annehulsey for reporting this issue - I just made the correction per your suggestion which I agree would address the error.  Also, I would add you and Francisco (@galvisf) to collaborators - not sure if this could help resolve your push permission deny.
